package cn.jbolt.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("user", "username", User.class);
		arp.addMapping("files", "id", Files.class);
		arp.addMapping("results", "id", Results.class);
		arp.addMapping("resultsmoss", "id", Resultsmoss.class);
		arp.addMapping("resultscount", "id", Resultscount.class);
		arp.addMapping("resultscount2", "id", Resultscount2.class);
	}
}

