package cn.jbolt.common.model;

import java.util.Date;
import java.util.List;

import cn.jbolt.common.model.base.BaseFiles;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Files extends BaseFiles<Files> {
	public static final Files dao = new Files().dao();
	
	public void saveFile(String id, String name, String path, String classes, String lesson, Date date) {
		// TODO Auto-generated method stub
		new Files().set("id", id).set("fileName", name).set("filePath", path).set("classNum", classes).set("lessonNum", lesson).set("createTime",date).save();
	}
	
	public List<Files> getFilesList() {
		return find("select * from files");
	}

	public List<Files> getFilesList(String classes, String lesson) {
		return find("select * from files where classNum = '" + classes + "' and lessonNum = '" + lesson  + "'");
	}
}
