package cn.jbolt.common.model;

import java.util.List;

import com.jfinal.plugin.activerecord.Db;

import cn.jbolt.common.model.base.BaseResultsmoss;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Resultsmoss extends BaseResultsmoss<Resultsmoss> {
	public static final Resultsmoss dao = new Resultsmoss().dao();
	
	/* 实现保存数据到数据库的功能 */
	public void saveResultsmoss(String fileA, String fileB, double score, int samelines) {
		// TODO Auto-generated method stub
		new Resultsmoss().set("fileA", fileA).set("fileB", fileB).set("score", score).set("sameLines", samelines).save();
	}
	
	/* 清空数据库数据*/
	public void deleteResultsList() {
		Db.update("truncate table resultsmoss");
		
	}
	
	/* 获取数据库数据*/
	public List<Resultsmoss> getResultsList() {
		return find("select * from resultsmoss order by score DESC");
	}
	

	public List<Resultsmoss> getResultsList(double lowScore ) {
		return find("select * from resultsmoss where score >= " + lowScore +" order by score DESC"); 
	}
	
	
}
