package cn.jbolt.common.model;

import java.util.Date;
import java.util.List;

import cn.jbolt.common.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User().dao();
	
	public List<User> findByNameAndPwd(String name, String password) {
		return find("select * from user where username='" + name + "' and password='" + password + "'");
	}

	/* 实现保存数据到数据库的功能 */
	public void saveUser(String name, String password, String email, Date date) {
		// TODO Auto-generated method stub
		new User().set("username", name).set("password", password).set("email", email).set("createTime",date).save();
	}

	
}
