package cn.jbolt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseFiles<M extends BaseFiles<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setFileName(java.lang.String fileName) {
		set("fileName", fileName);
		return (M)this;
	}
	
	public java.lang.String getFileName() {
		return getStr("fileName");
	}

	public M setFilePath(java.lang.String filePath) {
		set("filePath", filePath);
		return (M)this;
	}
	
	public java.lang.String getFilePath() {
		return getStr("filePath");
	}

	public M setClassNum(java.lang.String classNum) {
		set("classNum", classNum);
		return (M)this;
	}
	
	public java.lang.String getClassNum() {
		return getStr("classNum");
	}

	public M setLessonNum(java.lang.String lessonNum) {
		set("lessonNum", lessonNum);
		return (M)this;
	}
	
	public java.lang.String getLessonNum() {
		return getStr("lessonNum");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

}
