package cn.jbolt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseResultsmoss<M extends BaseResultsmoss<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setFileA(java.lang.String fileA) {
		set("fileA", fileA);
		return (M)this;
	}
	
	public java.lang.String getFileA() {
		return getStr("fileA");
	}

	public M setFileB(java.lang.String fileB) {
		set("fileB", fileB);
		return (M)this;
	}
	
	public java.lang.String getFileB() {
		return getStr("fileB");
	}

	public M setScore(java.lang.Double score) {
		set("score", score);
		return (M)this;
	}
	
	public java.lang.Double getScore() {
		return getDouble("score");
	}

	public M setSameLines(java.lang.Integer sameLines) {
		set("sameLines", sameLines);
		return (M)this;
	}
	
	public java.lang.Integer getSameLines() {
		return getInt("sameLines");
	}

}
